// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Crystal node type enum (u8NodeType field in crystal.wdb).
///
/// Defines what bonus a Crystarium node provides when unlocked.
/// The `u16NodeVal` field specifies the magnitude of the bonus.
///
/// # Values
///
/// | Value | Type       | NodeVal Meaning                    |
/// |-------|------------|-----------------------------------|
/// | 0     | None       | -                                 |
/// | 1     | Hp         | HP increase amount                |
/// | 2     | Strength   | Strength stat increase            |
/// | 3     | Magic      | Magic stat increase               |
/// | 4     | Accessory  | Accessory slot index              |
/// | 5     | AtbSegment | ATB gauge segment unlock          |
/// | 6     | Ability    | Ability ID reference              |
/// | 7     | Role       | Role level unlock                 |
enum CrystalNodeType {
  none,
  hp,
  strength,
  magic,
  accessory,
  atbSegment,
  ability,
  role,
  ;
}

/// Crystal role enum (u4Role field in crystal.wdb).
///
/// Each node in the Crystarium belongs to one of six roles.
/// This determines which role level increases when unlocking nodes.
///
/// # Values
///
/// | Value | Role      | Japanese | Description              |
/// |-------|-----------|----------|--------------------------|
/// | 0     | None      | -        | Not assigned to a role   |
/// | 1     | Defender  | 聖騎士   | Sentinel                 |
/// | 2     | Attacker  | アタッカー | Commando               |
/// | 3     | Blaster   | ブラスター | Ravager                |
/// | 4     | Enhancer  | エンハンサー | Synergist            |
/// | 5     | Jammer    | ジャマー | Saboteur                 |
/// | 6     | Healer    | ヒーラー | Medic                    |
enum CrystalRole {
  none,
  defender,
  attacker,
  blaster,
  enhancer,
  jammer,
  healer,
  ;
}
