// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'enums.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'structs.freezed.dart';

class WdbData {
  final Map<String, WdbValue> header;
  final List<Map<String, WdbValue>> records;

  const WdbData({
    required this.header,
    required this.records,
  });

  @override
  int get hashCode => header.hashCode ^ records.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WdbData &&
          runtimeType == other.runtimeType &&
          header == other.header &&
          records == other.records;
}

@freezed
sealed class WdbValue with _$WdbValue {
  const WdbValue._();

  const factory WdbValue.int(
    int field0,
  ) = WdbValue_Int;
  const factory WdbValue.uInt(
    int field0,
  ) = WdbValue_UInt;
  const factory WdbValue.float(
    double field0,
  ) = WdbValue_Float;
  const factory WdbValue.string(
    String field0,
  ) = WdbValue_String;
  const factory WdbValue.bool(
    bool field0,
  ) = WdbValue_Bool;
  const factory WdbValue.intArray(
    Int32List field0,
  ) = WdbValue_IntArray;
  const factory WdbValue.uIntArray(
    Uint32List field0,
  ) = WdbValue_UIntArray;
  const factory WdbValue.stringArray(
    List<String> field0,
  ) = WdbValue_StringArray;
  const factory WdbValue.crystalRole(
    CrystalRole field0,
  ) = WdbValue_CrystalRole;
  const factory WdbValue.crystalNodeType(
    CrystalNodeType field0,
  ) = WdbValue_CrystalNodeType;
  const factory WdbValue.unknown() = WdbValue_Unknown;
}
