// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'battle_ability.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BattleAbility _$BattleAbilityFromJson(
  Map<String, dynamic> json,
) => BattleAbility(
  stringResId: json['sStringResId'] as String? ?? '',
  infoStResId: json['sInfoStResId'] as String? ?? '',
  scriptId: json['sScriptId'] as String? ?? '',
  ablArgStr0: json['sAblArgStr0'] as String? ?? '',
  ablArgStr1: json['sAblArgStr1'] as String? ?? '',
  autoAblStEff0: json['sAutoAblStEff0'] as String? ?? '',
  distanceMin: (json['fDistanceMin'] as num?)?.toDouble() ?? 0.0,
  distanceMax: (json['fDistanceMax'] as num?)?.toDouble() ?? 0.0,
  maxJumpHeight: (json['fMaxJumpHeight'] as num?)?.toDouble() ?? 0.0,
  yDistanceMin: (json['fYDistanceMin'] as num?)?.toDouble() ?? 0.0,
  yDistanceMax: (json['fYDistanceMax'] as num?)?.toDouble() ?? 0.0,
  airJpHeight: (json['fAirJpHeight'] as num?)?.toDouble() ?? 0.0,
  airJpTime: (json['fAirJpTime'] as num?)?.toDouble() ?? 0.0,
  replaceAirAttack: json['sReplaceAirAttack'] as String? ?? '',
  replaceAirAir: json['sReplaceAirAir'] as String? ?? '',
  replaceRangeAtk: json['sReplaceRangeAtk'] as String? ?? '',
  replaceFinAtk: json['sReplaceFinAtk'] as String? ?? '',
  replaceEnAttr: json['sReplaceEnAttr'] as String? ?? '',
  exceptionID: (json['iExceptionID'] as num?)?.toInt() ?? 0,
  actionId0: json['sActionId0'] as String? ?? '',
  actionId1: json['sActionId1'] as String? ?? '',
  actionId2: json['sActionId2'] as String? ?? '',
  actionId3: json['sActionId3'] as String? ?? '',
  rtDamSrc: json['sRtDamSrc'] as String? ?? '',
  refDamSrc: json['sRefDamSrc'] as String? ?? '',
  subRefDamSrc: json['sSubRefDamSrc'] as String? ?? '',
  slamDamSrc: json['sSlamDamSrc'] as String? ?? '',
  camArtsSeqId0: json['sCamArtsSeqId0'] as String? ?? '',
  camArtsSeqId1: json['sCamArtsSeqId1'] as String? ?? '',
  camArtsSeqId2: json['sCamArtsSeqId2'] as String? ?? '',
  camArtsSeqId3: json['sCamArtsSeqId3'] as String? ?? '',
  redirectAbility0: json['sRedirectAbility0'] as String? ?? '',
  redirectTo0: json['sRedirectTo0'] as String? ?? '',
  redirectAbility1: json['sRedirectAbility1'] as String? ?? '',
  redirectTo1: json['sRedirectTo1'] as String? ?? '',
  redirectAbility2: json['sRedirectAbility2'] as String? ?? '',
  redirectTo2: json['sRedirectTo2'] as String? ?? '',
  redirectAbility3: json['sRedirectAbility3'] as String? ?? '',
  redirectTo3: json['sRedirectTo3'] as String? ?? '',
  sysEffId0: json['sSysEffId0'] as String? ?? '',
  sysEffArg0: (json['iSysEffArg0'] as num?)?.toInt() ?? 0,
  sysSndId0: json['sSysSndId0'] as String? ?? '',
  rtEffId0: json['sRtEffId0'] as String? ?? '',
  rtEffArg0: (json['iRtEffArg0'] as num?)?.toInt() ?? 0,
  rtSndId0: json['sRtSndId0'] as String? ?? '',
  rtEffId1: json['sRtEffId1'] as String? ?? '',
  rtEffArg1: (json['iRtEffArg1'] as num?)?.toInt() ?? 0,
  rtSndId1: json['sRtSndId1'] as String? ?? '',
  rtEffId2: json['sRtEffId2'] as String? ?? '',
  rtEffArg2: (json['iRtEffArg2'] as num?)?.toInt() ?? 0,
  rtSndId2: json['sRtSndId2'] as String? ?? '',
  rtEffId3: json['sRtEffId3'] as String? ?? '',
  rtEffArg3: (json['iRtEffArg3'] as num?)?.toInt() ?? 0,
  rtSndId3: json['sRtSndId3'] as String? ?? '',
  rtEffId4: json['sRtEffId4'] as String? ?? '',
  rtEffArg4: (json['iRtEffArg4'] as num?)?.toInt() ?? 0,
  rtSndId4: json['sRtSndId4'] as String? ?? '',
  comAbility: const BoolIntConverter().fromJson(json['u1ComAbility']),
  rsvFlag0: const BoolIntConverter().fromJson(json['u1RsvFlag0']),
  rsvFlag1: const BoolIntConverter().fromJson(json['u1RsvFlag1']),
  rsvFlag2: const BoolIntConverter().fromJson(json['u1RsvFlag2']),
  rsvFlag3: const BoolIntConverter().fromJson(json['u1RsvFlag3']),
  rsvFlag4: const BoolIntConverter().fromJson(json['u1RsvFlag4']),
  rsvFlag5: const BoolIntConverter().fromJson(json['u1RsvFlag5']),
  rsvFlag6: const BoolIntConverter().fromJson(json['u1RsvFlag6']),
  artsNameHideKd: (json['u4ArtsNameHideKd'] as num?)?.toInt() ?? 0,
  artsNameFrame: (json['u16ArtsNameFrame'] as num?)?.toInt() ?? 0,
  useRole: (json['u4UseRole'] as num?)?.toInt() ?? 0,
  ablSndKind: (json['u8AblSndKind'] as num?)?.toInt() ?? 0,
  menuCategory: (json['u4MenuCategory'] as num?)?.toInt() ?? 0,
  menuSortNo: (json['i16MenuSortNo'] as num?)?.toInt() ?? 0,
  noDespel: const BoolIntConverter().fromJson(json['u1NoDespel']),
  scriptArg0: (json['i16ScriptArg0'] as num?)?.toInt() ?? 0,
  scriptArg1: (json['i16ScriptArg1'] as num?)?.toInt() ?? 0,
  abilityKind: (json['u8AbilityKind'] as num?)?.toInt() ?? 0,
  targetListKind: (json['u4TargetListKind'] as num?)?.toInt() ?? 0,
  ablArgInt0: (json['i16AblArgInt0'] as num?)?.toInt() ?? 0,
  upAblKind: (json['u4UpAblKind'] as num?)?.toInt() ?? 0,
  ablArgInt1: (json['i16AblArgInt1'] as num?)?.toInt() ?? 0,
  atbCount: (json['i16AtbCount'] as num?)?.toInt() ?? 0,
  atRnd: (json['i16AtRnd'] as num?)?.toInt() ?? 0,
  keepVal: (json['i16KeepVal'] as num?)?.toInt() ?? 0,
  intRsv0: (json['i16IntRsv0'] as num?)?.toInt() ?? 0,
  intRsv1: (json['i16IntRsv1'] as num?)?.toInt() ?? 0,
  tgFoge: const BoolIntConverter().fromJson(json['u1TgFoge']),
  noBackStep: const BoolIntConverter().fromJson(json['u1NoBackStep']),
  aiWanderFlag: const BoolIntConverter().fromJson(json['u1AIWanderFlag']),
  tgElemId: (json['u16TgElemId'] as num?)?.toInt() ?? 0,
  opProp0: (json['u10OpProp0'] as num?)?.toInt() ?? 0,
  autoAblStEfEd0: const BoolIntConverter().fromJson(json['u1AutoAblStEfEd0']),
  checkAutoRpl: const BoolIntConverter().fromJson(json['u1CheckAutoRpl']),
  seqParts: const BoolIntConverter().fromJson(json['u1SeqParts']),
  autoAblStEfTi0: (json['i16AutoAblStEfTi0'] as num?)?.toInt() ?? 0,
  yRgCheckType: (json['u4YRgCheckType'] as num?)?.toInt() ?? 0,
  atDistKind: (json['u4AtDistKind'] as num?)?.toInt() ?? 0,
  jumpAttackType: (json['u4JumpAttackType'] as num?)?.toInt() ?? 0,
  seqTermination: const BoolIntConverter().fromJson(json['u1SeqTermination']),
  actSelType: (json['u5ActSelType'] as num?)?.toInt() ?? 0,
  loopFinCond: (json['u4LoopFinCond'] as num?)?.toInt() ?? 0,
  loopFinArg: (json['u16LoopFinArg'] as num?)?.toInt() ?? 0,
  redirectMargeNof0: (json['u4RedirectMargeNof0'] as num?)?.toInt() ?? 0,
  refDamSrcRpt: (json['i16RefDamSrcRpt'] as num?)?.toInt() ?? 0,
  subRefDamSrcRp: (json['i16SubRefDamSrcRp'] as num?)?.toInt() ?? 0,
  areaRad: (json['i8AreaRad'] as num?)?.toInt() ?? 0,
  camArtsSelType: (json['u8CamArtsSelType'] as num?)?.toInt() ?? 0,
  redirectMargeNof1: (json['u4RedirectMargeNof1'] as num?)?.toInt() ?? 0,
  redirectMargeNof2: (json['u4RedirectMargeNof2'] as num?)?.toInt() ?? 0,
  redirectMargeNof3: (json['u4RedirectMargeNof3'] as num?)?.toInt() ?? 0,
  sysEffPos0: (json['u16SysEffPos0'] as num?)?.toInt() ?? 0,
  rtEffPos0: (json['u16RtEffPos0'] as num?)?.toInt() ?? 0,
  rtEffPos1: (json['u16RtEffPos1'] as num?)?.toInt() ?? 0,
  rtEffPos2: (json['u16RtEffPos2'] as num?)?.toInt() ?? 0,
  rtEffPos3: (json['u16RtEffPos3'] as num?)?.toInt() ?? 0,
  rtEffPos4: (json['u16RtEffPos4'] as num?)?.toInt() ?? 0,
);

Map<String, dynamic> _$BattleAbilityToJson(
  BattleAbility instance,
) => <String, dynamic>{
  'sStringResId': instance.stringResId,
  'sInfoStResId': instance.infoStResId,
  'sScriptId': instance.scriptId,
  'sAblArgStr0': instance.ablArgStr0,
  'sAblArgStr1': instance.ablArgStr1,
  'sAutoAblStEff0': instance.autoAblStEff0,
  'fDistanceMin': instance.distanceMin,
  'fDistanceMax': instance.distanceMax,
  'fMaxJumpHeight': instance.maxJumpHeight,
  'fYDistanceMin': instance.yDistanceMin,
  'fYDistanceMax': instance.yDistanceMax,
  'fAirJpHeight': instance.airJpHeight,
  'fAirJpTime': instance.airJpTime,
  'sReplaceAirAttack': instance.replaceAirAttack,
  'sReplaceAirAir': instance.replaceAirAir,
  'sReplaceRangeAtk': instance.replaceRangeAtk,
  'sReplaceFinAtk': instance.replaceFinAtk,
  'sReplaceEnAttr': instance.replaceEnAttr,
  'iExceptionID': instance.exceptionID,
  'sActionId0': instance.actionId0,
  'sActionId1': instance.actionId1,
  'sActionId2': instance.actionId2,
  'sActionId3': instance.actionId3,
  'sRtDamSrc': instance.rtDamSrc,
  'sRefDamSrc': instance.refDamSrc,
  'sSubRefDamSrc': instance.subRefDamSrc,
  'sSlamDamSrc': instance.slamDamSrc,
  'sCamArtsSeqId0': instance.camArtsSeqId0,
  'sCamArtsSeqId1': instance.camArtsSeqId1,
  'sCamArtsSeqId2': instance.camArtsSeqId2,
  'sCamArtsSeqId3': instance.camArtsSeqId3,
  'sRedirectAbility0': instance.redirectAbility0,
  'sRedirectTo0': instance.redirectTo0,
  'sRedirectAbility1': instance.redirectAbility1,
  'sRedirectTo1': instance.redirectTo1,
  'sRedirectAbility2': instance.redirectAbility2,
  'sRedirectTo2': instance.redirectTo2,
  'sRedirectAbility3': instance.redirectAbility3,
  'sRedirectTo3': instance.redirectTo3,
  'sSysEffId0': instance.sysEffId0,
  'iSysEffArg0': instance.sysEffArg0,
  'sSysSndId0': instance.sysSndId0,
  'sRtEffId0': instance.rtEffId0,
  'iRtEffArg0': instance.rtEffArg0,
  'sRtSndId0': instance.rtSndId0,
  'sRtEffId1': instance.rtEffId1,
  'iRtEffArg1': instance.rtEffArg1,
  'sRtSndId1': instance.rtSndId1,
  'sRtEffId2': instance.rtEffId2,
  'iRtEffArg2': instance.rtEffArg2,
  'sRtSndId2': instance.rtSndId2,
  'sRtEffId3': instance.rtEffId3,
  'iRtEffArg3': instance.rtEffArg3,
  'sRtSndId3': instance.rtSndId3,
  'sRtEffId4': instance.rtEffId4,
  'iRtEffArg4': instance.rtEffArg4,
  'sRtSndId4': instance.rtSndId4,
  'u1ComAbility': const BoolIntConverter().toJson(instance.comAbility),
  'u1RsvFlag0': const BoolIntConverter().toJson(instance.rsvFlag0),
  'u1RsvFlag1': const BoolIntConverter().toJson(instance.rsvFlag1),
  'u1RsvFlag2': const BoolIntConverter().toJson(instance.rsvFlag2),
  'u1RsvFlag3': const BoolIntConverter().toJson(instance.rsvFlag3),
  'u1RsvFlag4': const BoolIntConverter().toJson(instance.rsvFlag4),
  'u1RsvFlag5': const BoolIntConverter().toJson(instance.rsvFlag5),
  'u1RsvFlag6': const BoolIntConverter().toJson(instance.rsvFlag6),
  'u4ArtsNameHideKd': instance.artsNameHideKd,
  'u16ArtsNameFrame': instance.artsNameFrame,
  'u4UseRole': instance.useRole,
  'u8AblSndKind': instance.ablSndKind,
  'u4MenuCategory': instance.menuCategory,
  'i16MenuSortNo': instance.menuSortNo,
  'u1NoDespel': const BoolIntConverter().toJson(instance.noDespel),
  'i16ScriptArg0': instance.scriptArg0,
  'i16ScriptArg1': instance.scriptArg1,
  'u8AbilityKind': instance.abilityKind,
  'u4TargetListKind': instance.targetListKind,
  'i16AblArgInt0': instance.ablArgInt0,
  'u4UpAblKind': instance.upAblKind,
  'i16AblArgInt1': instance.ablArgInt1,
  'i16AtbCount': instance.atbCount,
  'i16AtRnd': instance.atRnd,
  'i16KeepVal': instance.keepVal,
  'i16IntRsv0': instance.intRsv0,
  'i16IntRsv1': instance.intRsv1,
  'u1TgFoge': const BoolIntConverter().toJson(instance.tgFoge),
  'u1NoBackStep': const BoolIntConverter().toJson(instance.noBackStep),
  'u1AIWanderFlag': const BoolIntConverter().toJson(instance.aiWanderFlag),
  'u16TgElemId': instance.tgElemId,
  'u10OpProp0': instance.opProp0,
  'u1AutoAblStEfEd0': const BoolIntConverter().toJson(instance.autoAblStEfEd0),
  'u1CheckAutoRpl': const BoolIntConverter().toJson(instance.checkAutoRpl),
  'u1SeqParts': const BoolIntConverter().toJson(instance.seqParts),
  'i16AutoAblStEfTi0': instance.autoAblStEfTi0,
  'u4YRgCheckType': instance.yRgCheckType,
  'u4AtDistKind': instance.atDistKind,
  'u4JumpAttackType': instance.jumpAttackType,
  'u1SeqTermination': const BoolIntConverter().toJson(instance.seqTermination),
  'u5ActSelType': instance.actSelType,
  'u4LoopFinCond': instance.loopFinCond,
  'u16LoopFinArg': instance.loopFinArg,
  'u4RedirectMargeNof0': instance.redirectMargeNof0,
  'i16RefDamSrcRpt': instance.refDamSrcRpt,
  'i16SubRefDamSrcRp': instance.subRefDamSrcRp,
  'i8AreaRad': instance.areaRad,
  'u8CamArtsSelType': instance.camArtsSelType,
  'u4RedirectMargeNof1': instance.redirectMargeNof1,
  'u4RedirectMargeNof2': instance.redirectMargeNof2,
  'u4RedirectMargeNof3': instance.redirectMargeNof3,
  'u16SysEffPos0': instance.sysEffPos0,
  'u16RtEffPos0': instance.rtEffPos0,
  'u16RtEffPos1': instance.rtEffPos1,
  'u16RtEffPos2': instance.rtEffPos2,
  'u16RtEffPos3': instance.rtEffPos3,
  'u16RtEffPos4': instance.rtEffPos4,
};
