// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'item_weapon.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ItemWeapon _$ItemWeaponFromJson(Map<String, dynamic> json) => ItemWeapon(
  weaponCharaSpecId: json['sWeaponCharaSpecId'] as String? ?? '',
  weaponCharaSpecId2: json['sWeaponCharaSpecId2'] as String? ?? '',
  ability: json['sAbility'] as String? ?? '',
  ability2: json['sAbility2'] as String? ?? '',
  ability3: json['sAbility3'] as String? ?? '',
  upgradeAbility: json['sUpgradeAbility'] as String? ?? '',
  abilityHelpStringId: json['sAbilityHelpStringId'] as String? ?? '',
  buyPriceIncrement: (json['uBuyPriceIncrement'] as num?)?.toInt() ?? 0,
  sellPriceIncrement: (json['uSellPriceIncrement'] as num?)?.toInt() ?? 0,
  disasItem1: json['sDisasItem1'] as String? ?? '',
  disasItem2: json['sDisasItem2'] as String? ?? '',
  disasItem3: json['sDisasItem3'] as String? ?? '',
  disasItem4: json['sDisasItem4'] as String? ?? '',
  disasItem5: json['sDisasItem5'] as String? ?? '',
  unkVal1: (json['u8UnkVal1'] as num?)?.toInt() ?? 0,
  unkVal2: (json['u8UnkVal2'] as num?)?.toInt() ?? 0,
  unkVal3: (json['u2UnkVal3'] as num?)?.toInt() ?? 0,
  maxLvl: (json['u7MaxLvl'] as num?)?.toInt() ?? 0,
  unkVal4: (json['u4UnkVal4'] as num?)?.toInt() ?? 0,
  lightningCanWear: const BoolIntConverter().fromJson(json['u1LightCanWear']),
  sazCanWear: const BoolIntConverter().fromJson(json['u1SazCanWear']),
  snowCanWear: const BoolIntConverter().fromJson(json['u1SnowCanWear']),
  expRate1: (json['i10ExpRate1'] as num?)?.toInt() ?? 0,
  expRate2: (json['i10ExpRate2'] as num?)?.toInt() ?? 0,
  expRate3: (json['i10ExpRate3'] as num?)?.toInt() ?? 0,
  unkownBool4: const BoolIntConverter().fromJson(json['u1UnkBool4']),
  hopeCanWear: const BoolIntConverter().fromJson(json['u1HopeCanWear']),
  statusModKind0: (json['u8StatusModKind0'] as num?)?.toInt() ?? 0,
  statusModKind1: (json['u8StatusModKind1'] as num?)?.toInt() ?? 0,
  statusModType: (json['u4StatusModType'] as num?)?.toInt() ?? 0,
  fangCanWear: const BoolIntConverter().fromJson(json['u1FangCanWear']),
  vanilleCanWear: const BoolIntConverter().fromJson(json['u1VanilleCanWear']),
  unkVal5: (json['u16UnkVal5'] as num?)?.toInt() ?? 0,
  statusModVal: (json['i16StatusModVal'] as num?)?.toInt() ?? 0,
  unkVal6: (json['u16UnkVal6'] as num?)?.toInt() ?? 0,
  attackModVal: (json['i16AttackModVal'] as num?)?.toInt() ?? 0,
  unkVal7: (json['u16UnkVal7'] as num?)?.toInt() ?? 0,
  magicModVal: (json['i16MagicModVal'] as num?)?.toInt() ?? 0,
  atbModVal: (json['i16AtbModVal'] as num?)?.toInt() ?? 0,
  unkVal8: (json['u16UnkVal8'] as num?)?.toInt() ?? 0,
  unkVal9: (json['u16UnkVal9'] as num?)?.toInt() ?? 0,
  unkVal10: (json['u16UnkVal10'] as num?)?.toInt() ?? 0,
  disasRate1: (json['u14DisasRate1'] as num?)?.toInt() ?? 0,
  unkVal11: (json['u7UnkVal11'] as num?)?.toInt() ?? 0,
  unkVal12: (json['u7UnkVal12'] as num?)?.toInt() ?? 0,
  disasRate2: (json['u14DisasRate2'] as num?)?.toInt() ?? 0,
  disasRate3: (json['u14DisasRate3'] as num?)?.toInt() ?? 0,
  unkVal13: (json['u7UnkVal13'] as num?)?.toInt() ?? 0,
  disasRate4: (json['u14DisasRate4'] as num?)?.toInt() ?? 0,
  unkVal14: (json['u7UnkVal14'] as num?)?.toInt() ?? 0,
  disasRate5: (json['u14DisasRate5'] as num?)?.toInt() ?? 0,
);

Map<String, dynamic> _$ItemWeaponToJson(
  ItemWeapon instance,
) => <String, dynamic>{
  'sWeaponCharaSpecId': instance.weaponCharaSpecId,
  'sWeaponCharaSpecId2': instance.weaponCharaSpecId2,
  'sAbility': instance.ability,
  'sAbility2': instance.ability2,
  'sAbility3': instance.ability3,
  'sUpgradeAbility': instance.upgradeAbility,
  'sAbilityHelpStringId': instance.abilityHelpStringId,
  'uBuyPriceIncrement': instance.buyPriceIncrement,
  'uSellPriceIncrement': instance.sellPriceIncrement,
  'sDisasItem1': instance.disasItem1,
  'sDisasItem2': instance.disasItem2,
  'sDisasItem3': instance.disasItem3,
  'sDisasItem4': instance.disasItem4,
  'sDisasItem5': instance.disasItem5,
  'u8UnkVal1': instance.unkVal1,
  'u8UnkVal2': instance.unkVal2,
  'u2UnkVal3': instance.unkVal3,
  'u7MaxLvl': instance.maxLvl,
  'u4UnkVal4': instance.unkVal4,
  'u1LightCanWear': const BoolIntConverter().toJson(instance.lightningCanWear),
  'u1SazCanWear': const BoolIntConverter().toJson(instance.sazCanWear),
  'u1SnowCanWear': const BoolIntConverter().toJson(instance.snowCanWear),
  'i10ExpRate1': instance.expRate1,
  'i10ExpRate2': instance.expRate2,
  'i10ExpRate3': instance.expRate3,
  'u1UnkBool4': const BoolIntConverter().toJson(instance.unkownBool4),
  'u1HopeCanWear': const BoolIntConverter().toJson(instance.hopeCanWear),
  'u8StatusModKind0': instance.statusModKind0,
  'u8StatusModKind1': instance.statusModKind1,
  'u4StatusModType': instance.statusModType,
  'u1FangCanWear': const BoolIntConverter().toJson(instance.fangCanWear),
  'u1VanilleCanWear': const BoolIntConverter().toJson(instance.vanilleCanWear),
  'u16UnkVal5': instance.unkVal5,
  'i16StatusModVal': instance.statusModVal,
  'u16UnkVal6': instance.unkVal6,
  'i16AttackModVal': instance.attackModVal,
  'u16UnkVal7': instance.unkVal7,
  'i16MagicModVal': instance.magicModVal,
  'i16AtbModVal': instance.atbModVal,
  'u16UnkVal8': instance.unkVal8,
  'u16UnkVal9': instance.unkVal9,
  'u16UnkVal10': instance.unkVal10,
  'u14DisasRate1': instance.disasRate1,
  'u7UnkVal11': instance.unkVal11,
  'u7UnkVal12': instance.unkVal12,
  'u14DisasRate2': instance.disasRate2,
  'u14DisasRate3': instance.disasRate3,
  'u7UnkVal13': instance.unkVal13,
  'u14DisasRate4': instance.disasRate4,
  'u7UnkVal14': instance.unkVal14,
  'u14DisasRate5': instance.disasRate5,
};
