// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shop.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Shop _$ShopFromJson(Map<String, dynamic> json) => Shop(
  flagItemId: json['sFlagItemId'] as String? ?? '',
  unlockEventID: json['sUnlockEventID'] as String? ?? '',
  shopNameLabel: json['sShopNameLabel'] as String? ?? '',
  signId: json['sSignId'] as String? ?? '',
  explanationLabel: json['sExplanationLabel'] as String? ?? '',
  unkStringVal1: json['sUnkStringVal1'] as String? ?? '',
  itemLabel1: json['sItemLabel1'] as String? ?? '',
  itemLabel2: json['sItemLabel2'] as String? ?? '',
  itemLabel3: json['sItemLabel3'] as String? ?? '',
  itemLabel4: json['sItemLabel4'] as String? ?? '',
  itemLabel5: json['sItemLabel5'] as String? ?? '',
  itemLabel6: json['sItemLabel6'] as String? ?? '',
  itemLabel7: json['sItemLabel7'] as String? ?? '',
  itemLabel8: json['sItemLabel8'] as String? ?? '',
  itemLabel9: json['sItemLabel9'] as String? ?? '',
  itemLabel10: json['sItemLabel10'] as String? ?? '',
  itemLabel11: json['sItemLabel11'] as String? ?? '',
  itemLabel12: json['sItemLabel12'] as String? ?? '',
  itemLabel13: json['sItemLabel13'] as String? ?? '',
  itemLabel14: json['sItemLabel14'] as String? ?? '',
  itemLabel15: json['sItemLabel15'] as String? ?? '',
  itemLabel16: json['sItemLabel16'] as String? ?? '',
  itemLabel17: json['sItemLabel17'] as String? ?? '',
  itemLabel18: json['sItemLabel18'] as String? ?? '',
  itemLabel19: json['sItemLabel19'] as String? ?? '',
  itemLabel20: json['sItemLabel20'] as String? ?? '',
  itemLabel21: json['sItemLabel21'] as String? ?? '',
  itemLabel22: json['sItemLabel22'] as String? ?? '',
  itemLabel23: json['sItemLabel23'] as String? ?? '',
  itemLabel24: json['sItemLabel24'] as String? ?? '',
  itemLabel25: json['sItemLabel25'] as String? ?? '',
  itemLabel26: json['sItemLabel26'] as String? ?? '',
  itemLabel27: json['sItemLabel27'] as String? ?? '',
  itemLabel28: json['sItemLabel28'] as String? ?? '',
  itemLabel29: json['sItemLabel29'] as String? ?? '',
  itemLabel30: json['sItemLabel30'] as String? ?? '',
  itemLabel31: json['sItemLabel31'] as String? ?? '',
  itemLabel32: json['sItemLabel32'] as String? ?? '',
  version: (json['u4Version'] as num?)?.toInt() ?? 0,
  zoneNum: (json['u13ZoneNum'] as num?)?.toInt() ?? 0,
);

Map<String, dynamic> _$ShopToJson(Shop instance) => <String, dynamic>{
  'sFlagItemId': instance.flagItemId,
  'sUnlockEventID': instance.unlockEventID,
  'sShopNameLabel': instance.shopNameLabel,
  'sSignId': instance.signId,
  'sExplanationLabel': instance.explanationLabel,
  'sUnkStringVal1': instance.unkStringVal1,
  'sItemLabel1': instance.itemLabel1,
  'sItemLabel2': instance.itemLabel2,
  'sItemLabel3': instance.itemLabel3,
  'sItemLabel4': instance.itemLabel4,
  'sItemLabel5': instance.itemLabel5,
  'sItemLabel6': instance.itemLabel6,
  'sItemLabel7': instance.itemLabel7,
  'sItemLabel8': instance.itemLabel8,
  'sItemLabel9': instance.itemLabel9,
  'sItemLabel10': instance.itemLabel10,
  'sItemLabel11': instance.itemLabel11,
  'sItemLabel12': instance.itemLabel12,
  'sItemLabel13': instance.itemLabel13,
  'sItemLabel14': instance.itemLabel14,
  'sItemLabel15': instance.itemLabel15,
  'sItemLabel16': instance.itemLabel16,
  'sItemLabel17': instance.itemLabel17,
  'sItemLabel18': instance.itemLabel18,
  'sItemLabel19': instance.itemLabel19,
  'sItemLabel20': instance.itemLabel20,
  'sItemLabel21': instance.itemLabel21,
  'sItemLabel22': instance.itemLabel22,
  'sItemLabel23': instance.itemLabel23,
  'sItemLabel24': instance.itemLabel24,
  'sItemLabel25': instance.itemLabel25,
  'sItemLabel26': instance.itemLabel26,
  'sItemLabel27': instance.itemLabel27,
  'sItemLabel28': instance.itemLabel28,
  'sItemLabel29': instance.itemLabel29,
  'sItemLabel30': instance.itemLabel30,
  'sItemLabel31': instance.itemLabel31,
  'sItemLabel32': instance.itemLabel32,
  'u4Version': instance.version,
  'u13ZoneNum': instance.zoneNum,
};
