// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Container for all records in a WPD file.
class WpdData {
  /// All records from the WPD file
  final List<WpdRecord> records;

  const WpdData({
    required this.records,
  });

  @override
  int get hashCode => records.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WpdData &&
          runtimeType == other.runtimeType &&
          records == other.records;
}

/// Parsed WPD record with loaded data.
///
/// Combines the header metadata with the actual file contents.
class WpdRecord {
  /// File name (without extension)
  final String name;

  /// File extension (empty string if none)
  final String extension_;

  /// Raw file data
  final Uint8List data;

  const WpdRecord({
    required this.name,
    required this.extension_,
    required this.data,
  });

  @override
  int get hashCode => name.hashCode ^ extension_.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WpdRecord &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          extension_ == other.extension_ &&
          data == other.data;
}
