// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Action to perform on the target file.
enum Action {
  /// Decrypt the file in place
  decrypt,

  /// Encrypt the file in place
  encrypt,

  /// Convert CLB to standard Java .class format
  clbToJava,

  /// Convert Java .class to CLB format
  javaToClb,
  ;
}

/// Target file type for cryptographic operations.
enum TargetType {
  /// WBT filelist (encrypted file index)
  fileList,

  /// CLB script file (encrypted bytecode)
  clb,
  ;
}
