// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Image metadata returned to Flutter after extraction.
///
/// This struct contains texture properties without the actual pixel data,
/// which is typically too large to pass efficiently through FFI.
///
/// # Usage
///
/// Returned by [`extract_img_to_dds`] and [`extract_img_to_memory`] to
/// provide texture information to the Flutter UI.
///
/// # Example
///
/// ```rust,ignore
/// let img_data = extract_img_to_dds(header, imgb, output)?;
/// println!("Texture: {}x{}, {} mips, format: {}",
///     img_data.width, img_data.height,
///     img_data.mip_count, img_data.format);
/// ```
class ImgData {
  /// Texture width in pixels
  final int width;

  /// Texture height in pixels
  final int height;

  /// Number of mipmap levels
  final int mipCount;

  /// Format name (debug representation of format code)
  final String format;

  const ImgData({
    required this.width,
    required this.height,
    required this.mipCount,
    required this.format,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ mipCount.hashCode ^ format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImgData &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          mipCount == other.mipCount &&
          format == other.format;
}
