// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'structs.freezed.dart';

@freezed
sealed class ActorType with _$ActorType {
  const ActorType._();

  /// Camera actor (CameraActor_###)
  const factory ActorType.camera() = ActorType_Camera;

  /// Sound emitter (SoundActor_###)
  const factory ActorType.sound() = ActorType_Sound;

  /// Visual effect (EffectActor_###)
  const factory ActorType.effect() = ActorType_Effect;

  /// Background music (BgmActor_###)
  const factory ActorType.bgm() = ActorType_Bgm;

  /// Character proxy (ProxyActor_####)
  const factory ActorType.proxy() = ActorType_Proxy;

  /// System/utility actor (System_####)
  const factory ActorType.system() = ActorType_System;

  /// Named character (e.g., "lightning", "p_lt")
  const factory ActorType.character(
    String field0,
  ) = ActorType_Character;

  /// Unknown actor type
  const factory ActorType.unknown(
    String field0,
  ) = ActorType_Unknown;
}

/// A single track entry within a block.
///
/// Represents one action/command in the block's timeline.
class BlockTrack {
  /// Entry size in bytes
  final int size;

  /// Track type
  final TrackType trackType;

  /// Raw type code
  final int typeCode;

  /// Entry flags
  final int flags;

  /// Entry index within the block
  final int index;

  /// Reference string (if any) - e.g., motion set name, dialogue key
  final String? reference;

  /// Start frame (if detected)
  final int? startFrame;

  /// Duration in frames (if detected)
  final int? durationFrames;

  /// Float values (for camera tracks with position/rotation)
  final Float32List floatValues;

  const BlockTrack({
    required this.size,
    required this.trackType,
    required this.typeCode,
    required this.flags,
    required this.index,
    this.reference,
    this.startFrame,
    this.durationFrames,
    required this.floatValues,
  });

  @override
  int get hashCode =>
      size.hashCode ^
      trackType.hashCode ^
      typeCode.hashCode ^
      flags.hashCode ^
      index.hashCode ^
      reference.hashCode ^
      startFrame.hashCode ^
      durationFrames.hashCode ^
      floatValues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockTrack &&
          runtimeType == other.runtimeType &&
          size == other.size &&
          trackType == other.trackType &&
          typeCode == other.typeCode &&
          flags == other.flags &&
          index == other.index &&
          reference == other.reference &&
          startFrame == other.startFrame &&
          durationFrames == other.durationFrames &&
          floatValues == other.floatValues;
}

/// Camera Control Block (SEDBCCB format).
///
/// Contains camera animation data.
class CameraControlBlock {
  /// Record name (from WPD, typically a hash like "E2a11b449e4656c")
  final String name;

  /// Source file this was loaded from
  final String sourceFile;

  /// Header size
  final int headerSize;

  /// Data size
  final int dataSize;

  /// Flags
  final int flags;

  const CameraControlBlock({
    required this.name,
    required this.sourceFile,
    required this.headerSize,
    required this.dataSize,
    required this.flags,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      sourceFile.hashCode ^
      headerSize.hashCode ^
      dataSize.hashCode ^
      flags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraControlBlock &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sourceFile == other.sourceFile &&
          headerSize == other.headerSize &&
          dataSize == other.dataSize &&
          flags == other.flags;
}

/// Dialogue entry reference.
///
/// Contains the record name which can be used to look up
/// the actual text in ZTR files.
class DialogueEntry {
  /// Record name (e.g., "ev_ddaa_080_01")
  final String recordName;

  /// Raw content from the record (typically timing labels like "a00")
  final String rawContent;

  /// ZTR key for lookup (typically "$" + record_name)
  final String ztrKey;

  const DialogueEntry({
    required this.recordName,
    required this.rawContent,
    required this.ztrKey,
  });

  @override
  int get hashCode =>
      recordName.hashCode ^ rawContent.hashCode ^ ztrKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DialogueEntry &&
          runtimeType == other.runtimeType &&
          recordName == other.recordName &&
          rawContent == other.rawContent &&
          ztrKey == other.ztrKey;
}

/// Actor participating in the cutscene.
class EventActor {
  /// Actor name (e.g., "CameraActor_001", "lightning")
  final String name;

  /// Actor type classification
  final ActorType actorType;

  /// Actor index in the cutscene
  final int index;

  /// Raw flags from @CACT section
  final int flags;

  const EventActor({
    required this.name,
    required this.actorType,
    required this.index,
    required this.flags,
  });

  @override
  int get hashCode =>
      name.hashCode ^ actorType.hashCode ^ index.hashCode ^ flags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventActor &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          actorType == other.actorType &&
          index == other.index &&
          flags == other.flags;
}

/// Execution block in the cutscene.
///
/// Each block is like a scene in a video editor, containing multiple
/// timeline tracks that control different aspects (camera, motion, sound, etc.)
class EventBlock {
  /// Block name (e.g., "c01", "Block000")
  final String name;

  /// Block ID
  final int id;

  /// Duration in frames (typically 30fps)
  final int durationFrames;

  /// Duration in seconds (calculated from frames @ 30fps)
  final double durationSeconds;

  /// Number of track entries in this block
  final int trackCount;

  /// Timeline track entries (commands/actions within this block)
  final List<BlockTrack> tracks;

  const EventBlock({
    required this.name,
    required this.id,
    required this.durationFrames,
    required this.durationSeconds,
    required this.trackCount,
    required this.tracks,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      id.hashCode ^
      durationFrames.hashCode ^
      durationSeconds.hashCode ^
      trackCount.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventBlock &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          id == other.id &&
          durationFrames == other.durationFrames &&
          durationSeconds == other.durationSeconds &&
          trackCount == other.trackCount &&
          tracks == other.tracks;
}

/// DataSet contents (animation and camera data from DataSet/*.bin files).
class EventDataSet {
  /// Motion control blocks (from mcb records)
  final List<MotionControlBlock> motionBlocks;

  /// Camera control blocks (from ccb records)
  final List<CameraControlBlock> cameraBlocks;

  /// Source files that were loaded
  final List<String> sourceFiles;

  const EventDataSet({
    required this.motionBlocks,
    required this.cameraBlocks,
    required this.sourceFiles,
  });

  @override
  int get hashCode =>
      motionBlocks.hashCode ^ cameraBlocks.hashCode ^ sourceFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventDataSet &&
          runtimeType == other.runtimeType &&
          motionBlocks == other.motionBlocks &&
          cameraBlocks == other.cameraBlocks &&
          sourceFiles == other.sourceFiles;
}

/// Parsed event file metadata.
///
/// This is the main output structure containing all extracted metadata
/// from an event file without loading animation curves or keyframes.
class EventMetadata {
  /// Event name (derived from filename)
  final String name;

  /// Source file path
  final String sourcePath;

  /// Total file size in bytes
  final BigInt fileSize;

  /// Number of WPD records
  final BigInt recordCount;

  /// WPD record list with names and sizes
  final List<WpdRecordInfo> wpdRecords;

  /// Schedule header info
  final ScheduleHeader? scheduleHeader;

  /// Section counts from SEDBSCB
  final SectionCounts sectionCounts;

  /// External resource references from cutreslist
  final List<ExternalResource> externalResources;

  /// Actors participating in the cutscene
  final List<EventActor> actors;

  /// Execution blocks
  final List<EventBlock> blocks;

  /// Resource references
  final List<EventResource> resources;

  /// Sound block info
  final List<SoundBlock> soundBlocks;

  /// Sound references (music, sfx, voice IDs)
  final List<SoundReference> soundReferences;

  /// Dialogue entries (record names, not resolved text)
  final List<DialogueEntry> dialogueEntries;

  /// DataSet contents (if DataSet directory exists)
  final EventDataSet? dataset;

  const EventMetadata({
    required this.name,
    required this.sourcePath,
    required this.fileSize,
    required this.recordCount,
    required this.wpdRecords,
    this.scheduleHeader,
    required this.sectionCounts,
    required this.externalResources,
    required this.actors,
    required this.blocks,
    required this.resources,
    required this.soundBlocks,
    required this.soundReferences,
    required this.dialogueEntries,
    this.dataset,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      sourcePath.hashCode ^
      fileSize.hashCode ^
      recordCount.hashCode ^
      wpdRecords.hashCode ^
      scheduleHeader.hashCode ^
      sectionCounts.hashCode ^
      externalResources.hashCode ^
      actors.hashCode ^
      blocks.hashCode ^
      resources.hashCode ^
      soundBlocks.hashCode ^
      soundReferences.hashCode ^
      dialogueEntries.hashCode ^
      dataset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventMetadata &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sourcePath == other.sourcePath &&
          fileSize == other.fileSize &&
          recordCount == other.recordCount &&
          wpdRecords == other.wpdRecords &&
          scheduleHeader == other.scheduleHeader &&
          sectionCounts == other.sectionCounts &&
          externalResources == other.externalResources &&
          actors == other.actors &&
          blocks == other.blocks &&
          resources == other.resources &&
          soundBlocks == other.soundBlocks &&
          soundReferences == other.soundReferences &&
          dialogueEntries == other.dialogueEntries &&
          dataset == other.dataset;
}

/// Resource reference from @CRES section.
class EventResource {
  /// Resource name
  final String name;

  /// Resource type (e.g., "schedul", "RIDTBL", "Effect", "String")
  final String resourceType;

  /// External hash if present (E-prefixed)
  final String? externalHash;

  const EventResource({
    required this.name,
    required this.resourceType,
    this.externalHash,
  });

  @override
  int get hashCode =>
      name.hashCode ^ resourceType.hashCode ^ externalHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventResource &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          resourceType == other.resourceType &&
          externalHash == other.externalHash;
}

/// Summary of event file for quick display.
class EventSummary {
  /// Event name
  final String name;

  /// Number of actors
  final BigInt actorCount;

  /// Number of blocks
  final BigInt blockCount;

  /// Number of resources
  final BigInt resourceCount;

  /// Number of dialogue entries
  final BigInt dialogueCount;

  /// Number of sound blocks
  final BigInt soundBlockCount;

  /// Total duration in seconds (sum of blocks)
  final double totalDurationSeconds;

  /// Whether DataSet is available
  final bool hasDataset;

  /// Number of motion control blocks in DataSet
  final BigInt motionBlockCount;

  /// Number of camera control blocks in DataSet
  final BigInt cameraBlockCount;

  const EventSummary({
    required this.name,
    required this.actorCount,
    required this.blockCount,
    required this.resourceCount,
    required this.dialogueCount,
    required this.soundBlockCount,
    required this.totalDurationSeconds,
    required this.hasDataset,
    required this.motionBlockCount,
    required this.cameraBlockCount,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      actorCount.hashCode ^
      blockCount.hashCode ^
      resourceCount.hashCode ^
      dialogueCount.hashCode ^
      soundBlockCount.hashCode ^
      totalDurationSeconds.hashCode ^
      hasDataset.hashCode ^
      motionBlockCount.hashCode ^
      cameraBlockCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventSummary &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          actorCount == other.actorCount &&
          blockCount == other.blockCount &&
          resourceCount == other.resourceCount &&
          dialogueCount == other.dialogueCount &&
          soundBlockCount == other.soundBlockCount &&
          totalDurationSeconds == other.totalDurationSeconds &&
          hasDataset == other.hasDataset &&
          motionBlockCount == other.motionBlockCount &&
          cameraBlockCount == other.cameraBlockCount;
}

/// External resource reference from cutreslist.
class ExternalResource {
  /// Resource name (e.g., "c206ddaa080_01")
  final String name;

  /// External hash (e.g., "Ee1f7a3fa43b982")
  final String hash;

  /// Resource category (derived from name prefix)
  final ResourceCategory category;

  const ExternalResource({
    required this.name,
    required this.hash,
    required this.category,
  });

  @override
  int get hashCode => name.hashCode ^ hash.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExternalResource &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          hash == other.hash &&
          category == other.category;
}

/// Result of extracting an event file.
class ExtractedEvent {
  /// Output directory path
  final String outputDir;

  /// Parsed metadata
  final EventMetadata metadata;

  /// List of extracted file paths
  final List<String> extractedFiles;

  const ExtractedEvent({
    required this.outputDir,
    required this.metadata,
    required this.extractedFiles,
  });

  @override
  int get hashCode =>
      outputDir.hashCode ^ metadata.hashCode ^ extractedFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractedEvent &&
          runtimeType == other.runtimeType &&
          outputDir == other.outputDir &&
          metadata == other.metadata &&
          extractedFiles == other.extractedFiles;
}

/// Motion Control Block (SEDBMCB format).
///
/// Contains animation/motion data for characters.
class MotionControlBlock {
  /// Record name (from WPD, typically a hash like "E4395e03ada853f")
  final String name;

  /// Source file this was loaded from
  final String sourceFile;

  /// Header size
  final int headerSize;

  /// Data size
  final int dataSize;

  /// Version
  final int version;

  /// Flags
  final int flags;

  const MotionControlBlock({
    required this.name,
    required this.sourceFile,
    required this.headerSize,
    required this.dataSize,
    required this.version,
    required this.flags,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      sourceFile.hashCode ^
      headerSize.hashCode ^
      dataSize.hashCode ^
      version.hashCode ^
      flags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MotionControlBlock &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sourceFile == other.sourceFile &&
          headerSize == other.headerSize &&
          dataSize == other.dataSize &&
          version == other.version &&
          flags == other.flags;
}

/// Category of external resource.
enum ResourceCategory {
  /// Event file (ev_xxx)
  event,

  /// Camera animation (c### prefix)
  camera,

  /// World/environment (w### prefix)
  world,

  /// Facial animation (f### prefix)
  facial,

  /// Normal/generic animation (n### prefix)
  normal,

  /// Block animation (b### prefix)
  block,

  /// Cutscene camera (ddaa###_c##)
  cutsceneCamera,

  /// Unknown category
  unknown,
  ;
}

/// SEDBSCB schedule header info.
class ScheduleHeader {
  /// Magic string (should be "SEDBSCB")
  final String magic;

  /// Version number
  final int version;

  /// Header size in bytes
  final int headerSize;

  /// Data size in bytes
  final int dataSize;

  const ScheduleHeader({
    required this.magic,
    required this.version,
    required this.headerSize,
    required this.dataSize,
  });

  @override
  int get hashCode =>
      magic.hashCode ^
      version.hashCode ^
      headerSize.hashCode ^
      dataSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScheduleHeader &&
          runtimeType == other.runtimeType &&
          magic == other.magic &&
          version == other.version &&
          headerSize == other.headerSize &&
          dataSize == other.dataSize;
}

/// Counts of each section type in SEDBSCB.
class SectionCounts {
  /// @CRST - Resource Structure Table
  final int crst;

  /// @CRES - Resources
  final int cres;

  /// @CATT - Attributes
  final int catt;

  /// @CCPT - Control Points
  final int ccpt;

  /// @CACT - Actors
  final int cact;

  /// @CDPT - Data Points
  final int cdpt;

  /// @CTRK - Tracks
  final int ctrk;

  /// @CBKT - Block Table
  final int cbkt;

  /// @CBLK - Blocks
  final int cblk;

  const SectionCounts({
    required this.crst,
    required this.cres,
    required this.catt,
    required this.ccpt,
    required this.cact,
    required this.cdpt,
    required this.ctrk,
    required this.cbkt,
    required this.cblk,
  });

  @override
  int get hashCode =>
      crst.hashCode ^
      cres.hashCode ^
      catt.hashCode ^
      ccpt.hashCode ^
      cact.hashCode ^
      cdpt.hashCode ^
      ctrk.hashCode ^
      cbkt.hashCode ^
      cblk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SectionCounts &&
          runtimeType == other.runtimeType &&
          crst == other.crst &&
          cres == other.cres &&
          catt == other.catt &&
          ccpt == other.ccpt &&
          cact == other.cact &&
          cdpt == other.cdpt &&
          ctrk == other.ctrk &&
          cbkt == other.cbkt &&
          cblk == other.cblk;
}

/// Sound block info from SRB section.
class SoundBlock {
  /// Block name (e.g., "Block000")
  final String name;

  /// Duration in samples
  final int durationSamples;

  /// Duration in seconds (assuming 44100Hz sample rate)
  final double durationSeconds;

  const SoundBlock({
    required this.name,
    required this.durationSamples,
    required this.durationSeconds,
  });

  @override
  int get hashCode =>
      name.hashCode ^ durationSamples.hashCode ^ durationSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoundBlock &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          durationSamples == other.durationSamples &&
          durationSeconds == other.durationSeconds;
}

/// Sound reference from SRB.
class SoundReference {
  /// Block name this sound belongs to
  final String blockName;

  /// Sound identifier
  final String soundId;

  /// Sound type
  final SoundType soundType;

  const SoundReference({
    required this.blockName,
    required this.soundId,
    required this.soundType,
  });

  @override
  int get hashCode =>
      blockName.hashCode ^ soundId.hashCode ^ soundType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoundReference &&
          runtimeType == other.runtimeType &&
          blockName == other.blockName &&
          soundId == other.soundId &&
          soundType == other.soundType;
}

/// Type of sound reference.
enum SoundType {
  /// Background music (music_xxx)
  music,

  /// Ambient/attribute sound (atb_xxx)
  ambient,

  /// Character voice/dialogue
  voice,

  /// Sound effect
  soundEffect,

  /// Unknown type
  unknown,
  ;
}

@freezed
sealed class TrackType with _$TrackType {
  const TrackType._();

  /// Motion set reference (type 0x0a02) - contains mset_xxx strings
  const factory TrackType.motionSet() = TrackType_MotionSet;

  /// Character set reference - contains chset_xxx strings
  const factory TrackType.characterSet() = TrackType_CharacterSet;

  /// Camera control (types 0x0c0c, 0x0e0c, 0x0f0c, 0x100c, etc.)
  const factory TrackType.camera() = TrackType_Camera;

  /// Sound/audio event (type 0x080a)
  const factory TrackType.sound() = TrackType_Sound;

  /// Music bus reference (type 0x6000) - contains music_bus_xxx strings
  const factory TrackType.musicBus() = TrackType_MusicBus;

  /// Dialogue reference (type 0x140a) - contains $event_xxx strings
  const factory TrackType.dialogue() = TrackType_Dialogue;

  /// Effect trigger
  const factory TrackType.effect() = TrackType_Effect;

  /// Event definition reference
  const factory TrackType.eventDef() = TrackType_EventDef;

  /// Actor control/activation
  const factory TrackType.actorControl() = TrackType_ActorControl;

  /// Unknown track type with raw type code
  const factory TrackType.unknown(
    int field0,
  ) = TrackType_Unknown;
}

/// WPD record info for display.
class WpdRecordInfo {
  /// Record name
  final String name;

  /// File extension
  final String extension_;

  /// Offset in file
  final int offset;

  /// Size in bytes
  final int size;

  const WpdRecordInfo({
    required this.name,
    required this.extension_,
    required this.offset,
    required this.size,
  });

  @override
  int get hashCode =>
      name.hashCode ^ extension_.hashCode ^ offset.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WpdRecordInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          extension_ == other.extension_ &&
          offset == other.offset &&
          size == other.size;
}
