// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'modules/crystalium/structs.dart';
import 'modules/event/structs.dart';
import 'modules/img/structs.dart';
import 'modules/scd/structs.dart';
import 'modules/vfx/structs.dart';
import 'modules/wct.dart';
import 'modules/wdb/enums.dart';
import 'modules/wdb/structs.dart';
import 'modules/wpd/structs.dart';
import 'modules/ztr/structs.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, McpPattern> dco_decode_Map_String_mcp_pattern_None(dynamic raw);

  @protected
  Map<String, WdbValue> dco_decode_Map_String_wdb_value_None(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<ZtrParseProgress> dco_decode_StreamSink_ztr_parse_progress_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Action dco_decode_action(dynamic raw);

  @protected
  ActorType dco_decode_actor_type(dynamic raw);

  @protected
  BlockTrack dco_decode_block_track(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CgtFile dco_decode_box_autoadd_cgt_file(dynamic raw);

  @protected
  EventDataSet dco_decode_box_autoadd_event_data_set(dynamic raw);

  @protected
  McpFile dco_decode_box_autoadd_mcp_file(dynamic raw);

  @protected
  ScheduleHeader dco_decode_box_autoadd_schedule_header(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  VfxMesh dco_decode_box_autoadd_vfx_mesh(dynamic raw);

  @protected
  WdbData dco_decode_box_autoadd_wdb_data(dynamic raw);

  @protected
  ZtrData dco_decode_box_autoadd_ztr_data(dynamic raw);

  @protected
  CameraControlBlock dco_decode_camera_control_block(dynamic raw);

  @protected
  CgtFile dco_decode_cgt_file(dynamic raw);

  @protected
  CrystalNodeType dco_decode_crystal_node_type(dynamic raw);

  @protected
  CrystalRole dco_decode_crystal_role(dynamic raw);

  @protected
  CrystariumEntry dco_decode_crystarium_entry(dynamic raw);

  @protected
  CrystariumNode dco_decode_crystarium_node(dynamic raw);

  @protected
  DecodedAudio dco_decode_decoded_audio(dynamic raw);

  @protected
  DialogueEntry dco_decode_dialogue_entry(dynamic raw);

  @protected
  EventActor dco_decode_event_actor(dynamic raw);

  @protected
  EventBlock dco_decode_event_block(dynamic raw);

  @protected
  EventDataSet dco_decode_event_data_set(dynamic raw);

  @protected
  EventMetadata dco_decode_event_metadata(dynamic raw);

  @protected
  EventResource dco_decode_event_resource(dynamic raw);

  @protected
  EventSummary dco_decode_event_summary(dynamic raw);

  @protected
  ExternalResource dco_decode_external_resource(dynamic raw);

  @protected
  ExtractedEvent dco_decode_extracted_event(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  F32Array2 dco_decode_f_32_array_2(dynamic raw);

  @protected
  F32Array3 dco_decode_f_32_array_3(dynamic raw);

  @protected
  F32Array4 dco_decode_f_32_array_4(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImgData dco_decode_img_data(dynamic raw);

  @protected
  List<Map<String, WdbValue>> dco_decode_list_Map_String_wdb_value_None(
      dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BlockTrack> dco_decode_list_block_track(dynamic raw);

  @protected
  List<CameraControlBlock> dco_decode_list_camera_control_block(dynamic raw);

  @protected
  List<CrystariumEntry> dco_decode_list_crystarium_entry(dynamic raw);

  @protected
  List<CrystariumNode> dco_decode_list_crystarium_node(dynamic raw);

  @protected
  List<DecodedAudio> dco_decode_list_decoded_audio(dynamic raw);

  @protected
  List<DialogueEntry> dco_decode_list_dialogue_entry(dynamic raw);

  @protected
  List<EventActor> dco_decode_list_event_actor(dynamic raw);

  @protected
  List<EventBlock> dco_decode_list_event_block(dynamic raw);

  @protected
  List<EventResource> dco_decode_list_event_resource(dynamic raw);

  @protected
  List<ExternalResource> dco_decode_list_external_resource(dynamic raw);

  @protected
  List<MotionControlBlock> dco_decode_list_motion_control_block(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw);

  @protected
  List<(String, McpPattern)> dco_decode_list_record_string_mcp_pattern(
      dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<(String, WdbValue)> dco_decode_list_record_string_wdb_value(dynamic raw);

  @protected
  List<ScdStreamInfo> dco_decode_list_scd_stream_info(dynamic raw);

  @protected
  List<SoundBlock> dco_decode_list_sound_block(dynamic raw);

  @protected
  List<SoundReference> dco_decode_list_sound_reference(dynamic raw);

  @protected
  List<Vec3> dco_decode_list_vec_3(dynamic raw);

  @protected
  List<VfxAnimation> dco_decode_list_vfx_animation(dynamic raw);

  @protected
  List<VfxEffect> dco_decode_list_vfx_effect(dynamic raw);

  @protected
  List<VfxModel> dco_decode_list_vfx_model(dynamic raw);

  @protected
  List<VfxTexture> dco_decode_list_vfx_texture(dynamic raw);

  @protected
  List<VfxVertex> dco_decode_list_vfx_vertex(dynamic raw);

  @protected
  List<WbtFileEntry> dco_decode_list_wbt_file_entry(dynamic raw);

  @protected
  List<WpdRecord> dco_decode_list_wpd_record(dynamic raw);

  @protected
  List<WpdRecordInfo> dco_decode_list_wpd_record_info(dynamic raw);

  @protected
  List<ZtrEntry> dco_decode_list_ztr_entry(dynamic raw);

  @protected
  List<ZtrEntryWithSource> dco_decode_list_ztr_entry_with_source(dynamic raw);

  @protected
  List<ZtrFileError> dco_decode_list_ztr_file_error(dynamic raw);

  @protected
  List<ZtrMapEntry> dco_decode_list_ztr_map_entry(dynamic raw);

  @protected
  McpFile dco_decode_mcp_file(dynamic raw);

  @protected
  McpPattern dco_decode_mcp_pattern(dynamic raw);

  @protected
  MotionControlBlock dco_decode_motion_control_block(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  EventDataSet? dco_decode_opt_box_autoadd_event_data_set(dynamic raw);

  @protected
  ScheduleHeader? dco_decode_opt_box_autoadd_schedule_header(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  VfxMesh? dco_decode_opt_box_autoadd_vfx_mesh(dynamic raw);

  @protected
  (ImgData, Uint8List) dco_decode_record_img_data_list_prim_u_8_strict(
      dynamic raw);

  @protected
  ((int, int), Uint8List)
      dco_decode_record_record_u_32_u_32_list_prim_u_8_strict(dynamic raw);

  @protected
  (String, McpPattern) dco_decode_record_string_mcp_pattern(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (String, WdbValue) dco_decode_record_string_wdb_value(dynamic raw);

  @protected
  (int, int) dco_decode_record_u_32_u_32(dynamic raw);

  @protected
  ResourceCategory dco_decode_resource_category(dynamic raw);

  @protected
  ScdCodec dco_decode_scd_codec(dynamic raw);

  @protected
  ScdExtractResult dco_decode_scd_extract_result(dynamic raw);

  @protected
  ScdHeader dco_decode_scd_header(dynamic raw);

  @protected
  ScdMetadata dco_decode_scd_metadata(dynamic raw);

  @protected
  ScdStreamInfo dco_decode_scd_stream_info(dynamic raw);

  @protected
  ScheduleHeader dco_decode_schedule_header(dynamic raw);

  @protected
  SectionCounts dco_decode_section_counts(dynamic raw);

  @protected
  SoundBlock dco_decode_sound_block(dynamic raw);

  @protected
  SoundReference dco_decode_sound_reference(dynamic raw);

  @protected
  SoundType dco_decode_sound_type(dynamic raw);

  @protected
  TargetType dco_decode_target_type(dynamic raw);

  @protected
  TrackType dco_decode_track_type(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  U32Array4 dco_decode_u_32_array_4(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Vec3 dco_decode_vec_3(dynamic raw);

  @protected
  VfxAnimation dco_decode_vfx_animation(dynamic raw);

  @protected
  VfxData dco_decode_vfx_data(dynamic raw);

  @protected
  VfxEffect dco_decode_vfx_effect(dynamic raw);

  @protected
  VfxMaterial dco_decode_vfx_material(dynamic raw);

  @protected
  VfxMesh dco_decode_vfx_mesh(dynamic raw);

  @protected
  VfxModel dco_decode_vfx_model(dynamic raw);

  @protected
  VfxPrimitiveType dco_decode_vfx_primitive_type(dynamic raw);

  @protected
  VfxSummary dco_decode_vfx_summary(dynamic raw);

  @protected
  VfxTexture dco_decode_vfx_texture(dynamic raw);

  @protected
  VfxVertex dco_decode_vfx_vertex(dynamic raw);

  @protected
  WbtFileEntry dco_decode_wbt_file_entry(dynamic raw);

  @protected
  WdbData dco_decode_wdb_data(dynamic raw);

  @protected
  WdbValue dco_decode_wdb_value(dynamic raw);

  @protected
  WpdData dco_decode_wpd_data(dynamic raw);

  @protected
  WpdRecord dco_decode_wpd_record(dynamic raw);

  @protected
  WpdRecordInfo dco_decode_wpd_record_info(dynamic raw);

  @protected
  ZtrData dco_decode_ztr_data(dynamic raw);

  @protected
  ZtrDirectoryResult dco_decode_ztr_directory_result(dynamic raw);

  @protected
  ZtrEntry dco_decode_ztr_entry(dynamic raw);

  @protected
  ZtrEntryWithSource dco_decode_ztr_entry_with_source(dynamic raw);

  @protected
  ZtrFileError dco_decode_ztr_file_error(dynamic raw);

  @protected
  ZtrMapEntry dco_decode_ztr_map_entry(dynamic raw);

  @protected
  ZtrParseProgress dco_decode_ztr_parse_progress(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, McpPattern> sse_decode_Map_String_mcp_pattern_None(
      SseDeserializer deserializer);

  @protected
  Map<String, WdbValue> sse_decode_Map_String_wdb_value_None(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<ZtrParseProgress> sse_decode_StreamSink_ztr_parse_progress_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Action sse_decode_action(SseDeserializer deserializer);

  @protected
  ActorType sse_decode_actor_type(SseDeserializer deserializer);

  @protected
  BlockTrack sse_decode_block_track(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CgtFile sse_decode_box_autoadd_cgt_file(SseDeserializer deserializer);

  @protected
  EventDataSet sse_decode_box_autoadd_event_data_set(
      SseDeserializer deserializer);

  @protected
  McpFile sse_decode_box_autoadd_mcp_file(SseDeserializer deserializer);

  @protected
  ScheduleHeader sse_decode_box_autoadd_schedule_header(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  VfxMesh sse_decode_box_autoadd_vfx_mesh(SseDeserializer deserializer);

  @protected
  WdbData sse_decode_box_autoadd_wdb_data(SseDeserializer deserializer);

  @protected
  ZtrData sse_decode_box_autoadd_ztr_data(SseDeserializer deserializer);

  @protected
  CameraControlBlock sse_decode_camera_control_block(
      SseDeserializer deserializer);

  @protected
  CgtFile sse_decode_cgt_file(SseDeserializer deserializer);

  @protected
  CrystalNodeType sse_decode_crystal_node_type(SseDeserializer deserializer);

  @protected
  CrystalRole sse_decode_crystal_role(SseDeserializer deserializer);

  @protected
  CrystariumEntry sse_decode_crystarium_entry(SseDeserializer deserializer);

  @protected
  CrystariumNode sse_decode_crystarium_node(SseDeserializer deserializer);

  @protected
  DecodedAudio sse_decode_decoded_audio(SseDeserializer deserializer);

  @protected
  DialogueEntry sse_decode_dialogue_entry(SseDeserializer deserializer);

  @protected
  EventActor sse_decode_event_actor(SseDeserializer deserializer);

  @protected
  EventBlock sse_decode_event_block(SseDeserializer deserializer);

  @protected
  EventDataSet sse_decode_event_data_set(SseDeserializer deserializer);

  @protected
  EventMetadata sse_decode_event_metadata(SseDeserializer deserializer);

  @protected
  EventResource sse_decode_event_resource(SseDeserializer deserializer);

  @protected
  EventSummary sse_decode_event_summary(SseDeserializer deserializer);

  @protected
  ExternalResource sse_decode_external_resource(SseDeserializer deserializer);

  @protected
  ExtractedEvent sse_decode_extracted_event(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  F32Array2 sse_decode_f_32_array_2(SseDeserializer deserializer);

  @protected
  F32Array3 sse_decode_f_32_array_3(SseDeserializer deserializer);

  @protected
  F32Array4 sse_decode_f_32_array_4(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImgData sse_decode_img_data(SseDeserializer deserializer);

  @protected
  List<Map<String, WdbValue>> sse_decode_list_Map_String_wdb_value_None(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BlockTrack> sse_decode_list_block_track(SseDeserializer deserializer);

  @protected
  List<CameraControlBlock> sse_decode_list_camera_control_block(
      SseDeserializer deserializer);

  @protected
  List<CrystariumEntry> sse_decode_list_crystarium_entry(
      SseDeserializer deserializer);

  @protected
  List<CrystariumNode> sse_decode_list_crystarium_node(
      SseDeserializer deserializer);

  @protected
  List<DecodedAudio> sse_decode_list_decoded_audio(
      SseDeserializer deserializer);

  @protected
  List<DialogueEntry> sse_decode_list_dialogue_entry(
      SseDeserializer deserializer);

  @protected
  List<EventActor> sse_decode_list_event_actor(SseDeserializer deserializer);

  @protected
  List<EventBlock> sse_decode_list_event_block(SseDeserializer deserializer);

  @protected
  List<EventResource> sse_decode_list_event_resource(
      SseDeserializer deserializer);

  @protected
  List<ExternalResource> sse_decode_list_external_resource(
      SseDeserializer deserializer);

  @protected
  List<MotionControlBlock> sse_decode_list_motion_control_block(
      SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer);

  @protected
  List<(String, McpPattern)> sse_decode_list_record_string_mcp_pattern(
      SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer);

  @protected
  List<(String, WdbValue)> sse_decode_list_record_string_wdb_value(
      SseDeserializer deserializer);

  @protected
  List<ScdStreamInfo> sse_decode_list_scd_stream_info(
      SseDeserializer deserializer);

  @protected
  List<SoundBlock> sse_decode_list_sound_block(SseDeserializer deserializer);

  @protected
  List<SoundReference> sse_decode_list_sound_reference(
      SseDeserializer deserializer);

  @protected
  List<Vec3> sse_decode_list_vec_3(SseDeserializer deserializer);

  @protected
  List<VfxAnimation> sse_decode_list_vfx_animation(
      SseDeserializer deserializer);

  @protected
  List<VfxEffect> sse_decode_list_vfx_effect(SseDeserializer deserializer);

  @protected
  List<VfxModel> sse_decode_list_vfx_model(SseDeserializer deserializer);

  @protected
  List<VfxTexture> sse_decode_list_vfx_texture(SseDeserializer deserializer);

  @protected
  List<VfxVertex> sse_decode_list_vfx_vertex(SseDeserializer deserializer);

  @protected
  List<WbtFileEntry> sse_decode_list_wbt_file_entry(
      SseDeserializer deserializer);

  @protected
  List<WpdRecord> sse_decode_list_wpd_record(SseDeserializer deserializer);

  @protected
  List<WpdRecordInfo> sse_decode_list_wpd_record_info(
      SseDeserializer deserializer);

  @protected
  List<ZtrEntry> sse_decode_list_ztr_entry(SseDeserializer deserializer);

  @protected
  List<ZtrEntryWithSource> sse_decode_list_ztr_entry_with_source(
      SseDeserializer deserializer);

  @protected
  List<ZtrFileError> sse_decode_list_ztr_file_error(
      SseDeserializer deserializer);

  @protected
  List<ZtrMapEntry> sse_decode_list_ztr_map_entry(SseDeserializer deserializer);

  @protected
  McpFile sse_decode_mcp_file(SseDeserializer deserializer);

  @protected
  McpPattern sse_decode_mcp_pattern(SseDeserializer deserializer);

  @protected
  MotionControlBlock sse_decode_motion_control_block(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  EventDataSet? sse_decode_opt_box_autoadd_event_data_set(
      SseDeserializer deserializer);

  @protected
  ScheduleHeader? sse_decode_opt_box_autoadd_schedule_header(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  VfxMesh? sse_decode_opt_box_autoadd_vfx_mesh(SseDeserializer deserializer);

  @protected
  (ImgData, Uint8List) sse_decode_record_img_data_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  ((int, int), Uint8List)
      sse_decode_record_record_u_32_u_32_list_prim_u_8_strict(
          SseDeserializer deserializer);

  @protected
  (String, McpPattern) sse_decode_record_string_mcp_pattern(
      SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer);

  @protected
  (String, WdbValue) sse_decode_record_string_wdb_value(
      SseDeserializer deserializer);

  @protected
  (int, int) sse_decode_record_u_32_u_32(SseDeserializer deserializer);

  @protected
  ResourceCategory sse_decode_resource_category(SseDeserializer deserializer);

  @protected
  ScdCodec sse_decode_scd_codec(SseDeserializer deserializer);

  @protected
  ScdExtractResult sse_decode_scd_extract_result(SseDeserializer deserializer);

  @protected
  ScdHeader sse_decode_scd_header(SseDeserializer deserializer);

  @protected
  ScdMetadata sse_decode_scd_metadata(SseDeserializer deserializer);

  @protected
  ScdStreamInfo sse_decode_scd_stream_info(SseDeserializer deserializer);

  @protected
  ScheduleHeader sse_decode_schedule_header(SseDeserializer deserializer);

  @protected
  SectionCounts sse_decode_section_counts(SseDeserializer deserializer);

  @protected
  SoundBlock sse_decode_sound_block(SseDeserializer deserializer);

  @protected
  SoundReference sse_decode_sound_reference(SseDeserializer deserializer);

  @protected
  SoundType sse_decode_sound_type(SseDeserializer deserializer);

  @protected
  TargetType sse_decode_target_type(SseDeserializer deserializer);

  @protected
  TrackType sse_decode_track_type(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  U32Array4 sse_decode_u_32_array_4(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Vec3 sse_decode_vec_3(SseDeserializer deserializer);

  @protected
  VfxAnimation sse_decode_vfx_animation(SseDeserializer deserializer);

  @protected
  VfxData sse_decode_vfx_data(SseDeserializer deserializer);

  @protected
  VfxEffect sse_decode_vfx_effect(SseDeserializer deserializer);

  @protected
  VfxMaterial sse_decode_vfx_material(SseDeserializer deserializer);

  @protected
  VfxMesh sse_decode_vfx_mesh(SseDeserializer deserializer);

  @protected
  VfxModel sse_decode_vfx_model(SseDeserializer deserializer);

  @protected
  VfxPrimitiveType sse_decode_vfx_primitive_type(SseDeserializer deserializer);

  @protected
  VfxSummary sse_decode_vfx_summary(SseDeserializer deserializer);

  @protected
  VfxTexture sse_decode_vfx_texture(SseDeserializer deserializer);

  @protected
  VfxVertex sse_decode_vfx_vertex(SseDeserializer deserializer);

  @protected
  WbtFileEntry sse_decode_wbt_file_entry(SseDeserializer deserializer);

  @protected
  WdbData sse_decode_wdb_data(SseDeserializer deserializer);

  @protected
  WdbValue sse_decode_wdb_value(SseDeserializer deserializer);

  @protected
  WpdData sse_decode_wpd_data(SseDeserializer deserializer);

  @protected
  WpdRecord sse_decode_wpd_record(SseDeserializer deserializer);

  @protected
  WpdRecordInfo sse_decode_wpd_record_info(SseDeserializer deserializer);

  @protected
  ZtrData sse_decode_ztr_data(SseDeserializer deserializer);

  @protected
  ZtrDirectoryResult sse_decode_ztr_directory_result(
      SseDeserializer deserializer);

  @protected
  ZtrEntry sse_decode_ztr_entry(SseDeserializer deserializer);

  @protected
  ZtrEntryWithSource sse_decode_ztr_entry_with_source(
      SseDeserializer deserializer);

  @protected
  ZtrFileError sse_decode_ztr_file_error(SseDeserializer deserializer);

  @protected
  ZtrMapEntry sse_decode_ztr_map_entry(SseDeserializer deserializer);

  @protected
  ZtrParseProgress sse_decode_ztr_parse_progress(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_mcp_pattern_None(
      Map<String, McpPattern> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_wdb_value_None(
      Map<String, WdbValue> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_ztr_parse_progress_Sse(
      RustStreamSink<ZtrParseProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_action(Action self, SseSerializer serializer);

  @protected
  void sse_encode_actor_type(ActorType self, SseSerializer serializer);

  @protected
  void sse_encode_block_track(BlockTrack self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cgt_file(CgtFile self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_event_data_set(
      EventDataSet self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mcp_file(McpFile self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_schedule_header(
      ScheduleHeader self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vfx_mesh(VfxMesh self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wdb_data(WdbData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ztr_data(ZtrData self, SseSerializer serializer);

  @protected
  void sse_encode_camera_control_block(
      CameraControlBlock self, SseSerializer serializer);

  @protected
  void sse_encode_cgt_file(CgtFile self, SseSerializer serializer);

  @protected
  void sse_encode_crystal_node_type(
      CrystalNodeType self, SseSerializer serializer);

  @protected
  void sse_encode_crystal_role(CrystalRole self, SseSerializer serializer);

  @protected
  void sse_encode_crystarium_entry(
      CrystariumEntry self, SseSerializer serializer);

  @protected
  void sse_encode_crystarium_node(
      CrystariumNode self, SseSerializer serializer);

  @protected
  void sse_encode_decoded_audio(DecodedAudio self, SseSerializer serializer);

  @protected
  void sse_encode_dialogue_entry(DialogueEntry self, SseSerializer serializer);

  @protected
  void sse_encode_event_actor(EventActor self, SseSerializer serializer);

  @protected
  void sse_encode_event_block(EventBlock self, SseSerializer serializer);

  @protected
  void sse_encode_event_data_set(EventDataSet self, SseSerializer serializer);

  @protected
  void sse_encode_event_metadata(EventMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_event_resource(EventResource self, SseSerializer serializer);

  @protected
  void sse_encode_event_summary(EventSummary self, SseSerializer serializer);

  @protected
  void sse_encode_external_resource(
      ExternalResource self, SseSerializer serializer);

  @protected
  void sse_encode_extracted_event(
      ExtractedEvent self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_32_array_2(F32Array2 self, SseSerializer serializer);

  @protected
  void sse_encode_f_32_array_3(F32Array3 self, SseSerializer serializer);

  @protected
  void sse_encode_f_32_array_4(F32Array4 self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_img_data(ImgData self, SseSerializer serializer);

  @protected
  void sse_encode_list_Map_String_wdb_value_None(
      List<Map<String, WdbValue>> self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_block_track(
      List<BlockTrack> self, SseSerializer serializer);

  @protected
  void sse_encode_list_camera_control_block(
      List<CameraControlBlock> self, SseSerializer serializer);

  @protected
  void sse_encode_list_crystarium_entry(
      List<CrystariumEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_crystarium_node(
      List<CrystariumNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_decoded_audio(
      List<DecodedAudio> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dialogue_entry(
      List<DialogueEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_event_actor(
      List<EventActor> self, SseSerializer serializer);

  @protected
  void sse_encode_list_event_block(
      List<EventBlock> self, SseSerializer serializer);

  @protected
  void sse_encode_list_event_resource(
      List<EventResource> self, SseSerializer serializer);

  @protected
  void sse_encode_list_external_resource(
      List<ExternalResource> self, SseSerializer serializer);

  @protected
  void sse_encode_list_motion_control_block(
      List<MotionControlBlock> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_strict(
      Int32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_16_strict(
      Uint16List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_usize_strict(
      Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_mcp_pattern(
      List<(String, McpPattern)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_wdb_value(
      List<(String, WdbValue)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_scd_stream_info(
      List<ScdStreamInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sound_block(
      List<SoundBlock> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sound_reference(
      List<SoundReference> self, SseSerializer serializer);

  @protected
  void sse_encode_list_vec_3(List<Vec3> self, SseSerializer serializer);

  @protected
  void sse_encode_list_vfx_animation(
      List<VfxAnimation> self, SseSerializer serializer);

  @protected
  void sse_encode_list_vfx_effect(
      List<VfxEffect> self, SseSerializer serializer);

  @protected
  void sse_encode_list_vfx_model(List<VfxModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_vfx_texture(
      List<VfxTexture> self, SseSerializer serializer);

  @protected
  void sse_encode_list_vfx_vertex(
      List<VfxVertex> self, SseSerializer serializer);

  @protected
  void sse_encode_list_wbt_file_entry(
      List<WbtFileEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_wpd_record(
      List<WpdRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_wpd_record_info(
      List<WpdRecordInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ztr_entry(List<ZtrEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ztr_entry_with_source(
      List<ZtrEntryWithSource> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ztr_file_error(
      List<ZtrFileError> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ztr_map_entry(
      List<ZtrMapEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_mcp_file(McpFile self, SseSerializer serializer);

  @protected
  void sse_encode_mcp_pattern(McpPattern self, SseSerializer serializer);

  @protected
  void sse_encode_motion_control_block(
      MotionControlBlock self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_event_data_set(
      EventDataSet? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_schedule_header(
      ScheduleHeader? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_vfx_mesh(
      VfxMesh? self, SseSerializer serializer);

  @protected
  void sse_encode_record_img_data_list_prim_u_8_strict(
      (ImgData, Uint8List) self, SseSerializer serializer);

  @protected
  void sse_encode_record_record_u_32_u_32_list_prim_u_8_strict(
      ((int, int), Uint8List) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_mcp_pattern(
      (String, McpPattern) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_wdb_value(
      (String, WdbValue) self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_32_u_32((int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_resource_category(
      ResourceCategory self, SseSerializer serializer);

  @protected
  void sse_encode_scd_codec(ScdCodec self, SseSerializer serializer);

  @protected
  void sse_encode_scd_extract_result(
      ScdExtractResult self, SseSerializer serializer);

  @protected
  void sse_encode_scd_header(ScdHeader self, SseSerializer serializer);

  @protected
  void sse_encode_scd_metadata(ScdMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_scd_stream_info(ScdStreamInfo self, SseSerializer serializer);

  @protected
  void sse_encode_schedule_header(
      ScheduleHeader self, SseSerializer serializer);

  @protected
  void sse_encode_section_counts(SectionCounts self, SseSerializer serializer);

  @protected
  void sse_encode_sound_block(SoundBlock self, SseSerializer serializer);

  @protected
  void sse_encode_sound_reference(
      SoundReference self, SseSerializer serializer);

  @protected
  void sse_encode_sound_type(SoundType self, SseSerializer serializer);

  @protected
  void sse_encode_target_type(TargetType self, SseSerializer serializer);

  @protected
  void sse_encode_track_type(TrackType self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32_array_4(U32Array4 self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vec_3(Vec3 self, SseSerializer serializer);

  @protected
  void sse_encode_vfx_animation(VfxAnimation self, SseSerializer serializer);

  @protected
  void sse_encode_vfx_data(VfxData self, SseSerializer serializer);

  @protected
  void sse_encode_vfx_effect(VfxEffect self, SseSerializer serializer);

  @protected
  void sse_encode_vfx_material(VfxMaterial self, SseSerializer serializer);

  @protected
  void sse_encode_vfx_mesh(VfxMesh self, SseSerializer serializer);

  @protected
  void sse_encode_vfx_model(VfxModel self, SseSerializer serializer);

  @protected
  void sse_encode_vfx_primitive_type(
      VfxPrimitiveType self, SseSerializer serializer);

  @protected
  void sse_encode_vfx_summary(VfxSummary self, SseSerializer serializer);

  @protected
  void sse_encode_vfx_texture(VfxTexture self, SseSerializer serializer);

  @protected
  void sse_encode_vfx_vertex(VfxVertex self, SseSerializer serializer);

  @protected
  void sse_encode_wbt_file_entry(WbtFileEntry self, SseSerializer serializer);

  @protected
  void sse_encode_wdb_data(WdbData self, SseSerializer serializer);

  @protected
  void sse_encode_wdb_value(WdbValue self, SseSerializer serializer);

  @protected
  void sse_encode_wpd_data(WpdData self, SseSerializer serializer);

  @protected
  void sse_encode_wpd_record(WpdRecord self, SseSerializer serializer);

  @protected
  void sse_encode_wpd_record_info(WpdRecordInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ztr_data(ZtrData self, SseSerializer serializer);

  @protected
  void sse_encode_ztr_directory_result(
      ZtrDirectoryResult self, SseSerializer serializer);

  @protected
  void sse_encode_ztr_entry(ZtrEntry self, SseSerializer serializer);

  @protected
  void sse_encode_ztr_entry_with_source(
      ZtrEntryWithSource self, SseSerializer serializer);

  @protected
  void sse_encode_ztr_file_error(ZtrFileError self, SseSerializer serializer);

  @protected
  void sse_encode_ztr_map_entry(ZtrMapEntry self, SseSerializer serializer);

  @protected
  void sse_encode_ztr_parse_progress(
      ZtrParseProgress self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
