// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import, invalid_internal_annotation, depend_on_referenced_packages

import 'frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class F32Array4 extends NonGrowableListView<double> {
  static const arraySize = 4;

  @internal
  Float32List get inner => _inner;
  final Float32List _inner;

  F32Array4(this._inner)
      : assert(_inner.length == arraySize),
        super(_inner);

  F32Array4.init() : this(Float32List(arraySize));
}

class U32Array4 extends NonGrowableListView<int> {
  static const arraySize = 4;

  @internal
  Uint32List get inner => _inner;
  final Uint32List _inner;

  U32Array4(this._inner)
      : assert(_inner.length == arraySize),
        super(_inner);

  U32Array4.init() : this(Uint32List(arraySize));
}
